import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import Nav from '@/components/Nav';
import RecoilContextProvider from '@/components/recoilContextProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import '@/config/amplify.config';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Book Haven',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilContextProvider>
          <Nav />
          <div className="bg-white text-gray-800 flex flex-1 flex-col">
            {children}
          </div>
          <Footer />
          <ToastContainer />
        </RecoilContextProvider>
      </body>
    </html>
  );
}
